searcher.lo: /home/snow/hobby/searcher/binding/php/searcher/searcher.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/snow/hobby/searcher/binding/php/searcher $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/snow/hobby/searcher/binding/php/searcher/searcher.c -o searcher.lo 
$(phplibdir)/searcher.la: ./searcher.la
	$(LIBTOOL) --mode=install cp ./searcher.la $(phplibdir)

./searcher.la: $(shared_objects_searcher) $(SEARCHER_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_searcher) $(SEARCHER_SHARED_LIBADD)

